
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1428, 853)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115);\n"
"background-color:rgb(255, 251, 228)")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(Form)
        self.checkBox_26.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_2.addWidget(self.checkBox_26, 0, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 1, 1, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 0, 3, 1, 1)
        self.checkBox_30 = QtWidgets.QCheckBox(Form)
        self.checkBox_30.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_2.addWidget(self.checkBox_30, 1, 2, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_2.addWidget(self.checkBox_10, 3, 1, 1, 1)
        self.checkBox_22 = QtWidgets.QCheckBox(Form)
        self.checkBox_22.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_2.addWidget(self.checkBox_22, 3, 3, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(Form)
        self.checkBox_20.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_2.addWidget(self.checkBox_20, 1, 3, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 4, 1, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 2, 1, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(Form)
        self.checkBox_17.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_2.addWidget(self.checkBox_17, 4, 2, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(Form)
        self.checkBox_21.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_2.addWidget(self.checkBox_21, 2, 3, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(Form)
        self.checkBox_15.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_2.addWidget(self.checkBox_15, 2, 2, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(Form)
        self.checkBox_16.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_2.addWidget(self.checkBox_16, 3, 2, 1, 1)
        self.checkBox_29 = QtWidgets.QCheckBox(Form)
        self.checkBox_29.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_29.setObjectName("checkBox_29")
        self.gridLayout_2.addWidget(self.checkBox_29, 6, 2, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(Form)
        self.checkBox_23.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_2.addWidget(self.checkBox_23, 4, 3, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(Form)
        self.checkBox_24.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_2.addWidget(self.checkBox_24, 7, 3, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 5, 3, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(Form)
        self.checkBox_25.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_2.addWidget(self.checkBox_25, 5, 2, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(Form)
        self.checkBox_18.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_2.addWidget(self.checkBox_18, 7, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(Form)
        self.checkBox_14.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_2.addWidget(self.checkBox_14, 6, 1, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(Form)
        self.checkBox_27.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_2.addWidget(self.checkBox_27, 6, 0, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(Form)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_2.addWidget(self.checkBox_32, 7, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 2, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(Form)
        self.checkBox_28.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_2.addWidget(self.checkBox_28, 7, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(Form)
        self.checkBox_31.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_2.addWidget(self.checkBox_31, 6, 3, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 1, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(Form)
        self.checkBox_19.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_2.addWidget(self.checkBox_19, 5, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 3, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setStyleSheet("font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 4, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(Form)
        self.checkBox_13.setStyleSheet(" font-size:20pt; color:rgb(136, 114, 115)")
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_2.addWidget(self.checkBox_13, 5, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font-size:36pt;\n"
"color:rgb(136, 114, 115);\n"
"backgrund-color:rgb(255, 255, 237)")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Checkbox"))
        self.checkBox_7.setText(_translate("Form", "ბრინჯი"))
        self.checkBox_26.setText(_translate("Form", "სტაფილო"))
        self.checkBox_8.setText(_translate("Form", "თევზი"))
        self.checkBox_12.setText(_translate("Form", "თაფლი"))
        self.checkBox_30.setText(_translate("Form", "ნიორი"))
        self.checkBox_10.setText(_translate("Form", "საქონლის ხორცი"))
        self.checkBox_22.setText(_translate("Form", "მარწყვი"))
        self.checkBox_20.setText(_translate("Form", "კაკაო"))
        self.checkBox_11.setText(_translate("Form", "ღორის ხორცი"))
        self.checkBox_9.setText(_translate("Form", "ქათმის ხორცი"))
        self.checkBox_17.setText(_translate("Form", "მწვანილი"))
        self.checkBox_21.setText(_translate("Form", "შოკოლადი"))
        self.checkBox_15.setText(_translate("Form", "პომიდორი"))
        self.checkBox_16.setText(_translate("Form", "ხახვი"))
        self.checkBox_29.setText(_translate("Form", "ზეთისხილი"))
        self.checkBox_23.setText(_translate("Form", "ვაშლი"))
        self.checkBox_24.setText(_translate("Form", "ავოკადო"))
        self.checkBox_2.setText(_translate("Form", "კაკალი"))
        self.checkBox_25.setText(_translate("Form", "კომბოსტო"))
        self.checkBox_18.setText(_translate("Form", "ბადრიჯანი"))
        self.checkBox.setText(_translate("Form", "მაწონი"))
        self.checkBox_14.setText(_translate("Form", "ყველი"))
        self.checkBox_27.setText(_translate("Form", "ნაღები"))
        self.checkBox_32.setText(_translate("Form", "ქათმის ფილე"))
        self.checkBox_6.setText(_translate("Form", "არაჟანი"))
        self.checkBox_28.setText(_translate("Form", "ხაჭო"))
        self.checkBox_31.setText(_translate("Form", "ბანანი"))
        self.checkBox_5.setText(_translate("Form", "რძე"))
        self.checkBox_19.setText(_translate("Form", "სოკო"))
        self.checkBox_4.setText(_translate("Form", "ფქვილი"))
        self.checkBox_3.setText(_translate("Form", "კვერცხი"))
        self.checkBox_13.setText(_translate("Form", "მაიონეზი"))
        self.pushButton.setText(_translate("Form", "ძებნა"))
        self.label.setText(_translate("Form", "      აირჩიეთ სასურველი ინგრედიენტები"))
import sys
from PyQt5.QtWidgets import QApplication, QWidget

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = QWidget()
    ui = Ui_Form()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
